<?php
use Drupal\Core\Extension\ThemeHandlerInterface;
use Drupal\Core\Extension\ExtensionPathResolverInterface;

/**
 * @file
 * Code principal du module test_sitraka_taram.
 */

/**
 * Implémentation de hook_cron().
 * Purge le cache à chaque exécution du cron.
 */
function test_sitraka_taram_cron() {
  \Drupal::logger('test_sitraka_taram')->notice('Purge du cache via cron.');
  drupal_flush_all_caches();
}
/**
 * Implements hook_theme().
 */

/**
 * Implémentation de hook_theme().
 */
function test_sitraka_taram_theme($existing, $type, $theme, $path) {
  $moduleHandler = \Drupal::service('extension.path.resolver');
  $template_path = $moduleHandler->getPath('module', 'test_sitraka_taram') . '/templates';

  return [
    'last_articles_block' => [
      'variables' => ['articles' => NULL],
      'template' => 'last-articles-block',
      'path' => $template_path,
    ],
  ];
}

